<a href="https://colab.research.google.com/github/MariaAkterKhadiza/PHITRON_AI-ML-B1/blob/main/DP_Module_10(pytorch).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.10.0+cpu


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Device name {torch.cude.get_device_name(0)}")

else:
    print("GPU is not available")


GPU is not available


In [ ]:
a = torch.empty(2,3)
a

tensor([[2.1715e-18, 2.3081e-12, 2.6302e+20],
        [6.1943e-04, 3.6022e-12, 6.9989e+22]])

In [ ]:
type(a)

torch.Tensor

Creating **Tensors** **bold text**

In [ ]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,3) #random values

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)  #same number e bar bar asbe ja ami chacci)/random value asbe na

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.eye(5) #identity matrix

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.arange(0,10,3)# (divisor)

tensor([0, 3, 6, 9])

In [ ]:
torch.linspace(1,10,10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

 Tensors  **shape**


In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[    140141344386448,           385525040,                   0],
        [                  0,                   0, 7310593858020254331]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x,dtype = torch.float32)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

**Data Types**

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1.0,2.0,3.0], dtype=torch.float32)

tensor([1., 2., 3.])

In [ ]:
x = x.to(torch.float32)
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
x.dtype

torch.float32

mathematical operations

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [ ]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x-2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [ ]:
x*2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [ ]:
x/2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [ ]:
#floor

x = x*10

In [ ]:
x//3

tensor([[ 3,  6, 10],
        [13, 16, 20]])

In [ ]:
x**2

tensor([[ 100,  400,  900],
        [1600, 2500, 3600]])

In [ ]:
x%2

tensor([[0, 0, 0],
        [0, 0, 0]])