In [2]:
arr = [1,2,3]
print(arr * 5)

arr =[x*5 for x in arr]
print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [4]:
#numpy
import numpy as np
arr1 = np.array([1,2,3])
arr1 = arr1 * 5
print(arr1)

[ 5 10 15]


In [9]:
# nd declaration
import numpy as np

# 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1.ndim)  # Output: 1 (1 dimension)

# 2D array
arr2 = np.array([
    [1, 2, 3, 4],  # row1
    [6, 7, 8, 9]   # row2
])
print(arr2.ndim)  # Output: 2 (2 dimensions)

# 3D array
arr3 = np.array([
    # first floor
    [
        [1, 2, 3, 4],  # row1
        [6, 7, 8, 9]   # row2
    ],
    # second floor
    [
        [1, 2, 3, 4],  # row1
        [6, 7, 8, 9]   # row2
    ]
])
print(arr3.ndim)  # Output: 3 (3 dimensions)


1
2
3


In [11]:
#array attributes

#dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)


#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)


#data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

#size
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
(5,)
(2, 4)
(2, 2, 4)
int64
int64
int64
5
8
16


In [18]:
#data type

arr9 = np.array([1,2,3,4,5])
print(arr9.dtype)

arr9 = np.array([1.5,2.5,3.5,4.5,5.5])
print(arr9.dtype)

arr9 = np.array([1,2,3,4,5.5])
#upcasting
print(arr9.dtype)

arr9 = np.array([1,2,3,4,'3'])
print(arr9.dtype)



int64
float64
float64
<U21


In [20]:
#selecting data type for an array
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int8)
print(arr.dtype)


int8


In [25]:
#list
lst = [10,20,30,40,50.5]

arr = np.array(lst,dtype=np.int32)

print(arr)
print(type(arr))
print(arr.dtype)



mixed_lst = [10,True,'hello',10.5]

# arr = np.array(mixed_lst)
# print(arr)
# print(type(arr))
# print(arr.dtype)


matrix = (
        [1, 2, 3, 4],  # row1
        [6, 7, 8, 9])


arr = np.array(matrix)
print(arr)
print(type(arr))
print(arr.dtype)

[10 20 30 40 50]
<class 'numpy.ndarray'>
int32
[[1 2 3 4]
 [6 7 8 9]]
<class 'numpy.ndarray'>
int64


In [ ]:
#np.

import numpy as np
arr = ([1,2,3,4,5])
arr = np.zeros(1,3)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


NameError: name 'np' is not defined